name = "stick-figure-platformer"
compatibility_date = "2023-10-16"

# Pages配置
[site]
bucket = "./"

# 开发环境设置
[dev]
port = 8788

# D1数据库绑定
[[d1_databases]]
binding = "DB" # 在代码中使用env.DB访问
database_name = "stick_figure_game" 
database_id = "put-your-database-id-here" # 需要根据实际的D1数据库ID替换 